catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import ProductsFeedView, ContactsView, IndexView, PostCreateView, FeedView, PostDetailView, \
    PostUpdateView, \
    PostDeleteView, ProductCreateView, ProductUpdateView, ProductDetailView, ProductDeleteView, Joke, VersionCreateView, \
    VersionUpdateView, VersionDeleteView, ProductVersionsView, AccessDeniedView, CategoryListView

app_name = 'catalog'


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('AccessDenied', AccessDeniedView.as_view(), name='denied'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('create/', PostCreateView.as_view(), name="create"),
    path('feed/', FeedView.as_view(), name='feed'),
    path('feed/<slug>/', PostDetailView.as_view(), name='post view'),
    path('feed/edit/<slug>', PostUpdateView.as_view(), name='update post'),
    path('feed/delete/<slug>', PostDeleteView.as_view(), name='delete post'),
    path('feed/products', ProductsFeedView.as_view(), name='products feed'),
    path('feed/products/create', ProductCreateView.as_view(), name='create product'),
    path('feed/products/update/<int:pk>', ProductUpdateView.as_view(), name='update product'),
    path('feed/products/product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product view'),
    path('feed/products/delete/<int:pk>', ProductDeleteView.as_view(), name='delete product'),
    path('joke/', Joke.as_view(), name='joke'),
    path('feed/products/create_version', VersionCreateView.as_view(), name='create version'),
    path('feed/products/edit_version/<int:pk>', VersionUpdateView.as_view(), name='update version'),
    path('feed/products/delete_version/<int:pk>', VersionDeleteView.as_view(), name='delete version'),
    path('feed/products/product/<int:pk>/versions/', ProductVersionsView.as_view(), name='versions of product'),
    path('feed/categories', CategoryListView.as_view(), name='categories'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, verification, UserDetailView, change_password, CheckEmail

app_name = UsersConfig.name


urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login_form.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<int:user_pk>/<verification_code>/', verification, name='verification'),
    path('checkemail', CheckEmail.as_view(), name='checkemail'),
    path('user/<int:pk>', UserDetailView.as_view(), name='user'),
    path('user/change_password/<int:user_pk>', change_password, name='change_password'),
]

catalog/models.py
import datetime

from django.db import models

from users.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    desc = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    desc = models.TextField(verbose_name='Описание')
    preview = models.ImageField(upload_to='previews/', verbose_name='Картинка', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', null=True, blank=True)
    price = models.IntegerField(verbose_name='Цена')
    date = models.DateTimeField(verbose_name='Дата добавления', null=True, blank=True)
    ChangeDate = models.DateTimeField(verbose_name='Дата последнего изменения', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор',
                               blank=True, null=True)
    is_published = models.BooleanField(default=False, verbose_name="признак публикации")

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Post(models.Model):
    title = models.CharField(max_length=50, verbose_name="Заголовок")
    slug = models.CharField(max_length=100, verbose_name="slug")
    text = models.TextField(verbose_name="содержимое")
    pic = models.ImageField(upload_to='previews/', verbose_name='Картинка', null=True, blank=True)
    date = models.DateTimeField(verbose_name="дата создания", auto_now_add=True)
    is_published = models.BooleanField(verbose_name="признак публикации")
    views = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор',
                               blank=True, null=True)

    def __str__(self):
        return self.slug

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Версия', null=True, blank=True)
    number = models.FloatField(default=1, verbose_name='Номер версии')
    name = models.CharField(max_length=50, verbose_name='Название версии')
    is_active = models.BooleanField(verbose_name='Признак активной версии')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('ChangeDate', 'date', 'author', )

        def clean_name(self):
            cleaned_data = self.cleaned_data['name']
            forbidden = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно',
                         'обман', 'полиция', 'радар']

            if any(x in cleaned_data for x in forbidden):
                raise forms.ValidationError('Проверьте название на наличие запрещенных на сайте слов')

            return cleaned_data


class ProductModerForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('desc', 'is_published', 'category', )


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views import View
from django.views.generic import ListView, TemplateView, CreateView, DetailView, UpdateView, DeleteView
from catalog.services import GetCachedCategories

from catalog.forms import ProductForm, VersionForm, ProductModerForm
from catalog.models import Product, Post, Version, Category


# Create your views here.


class AccessDeniedView(TemplateView):
    template_name = 'catalog/access_denied.html'


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'


class IndexView(TemplateView):
    template_name = 'catalog/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['products'] = Product.objects.all()
        return context_data


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ("title", "text", "pic", "is_published", )
    success_url = reverse_lazy('catalog:feed')
    template_name = 'catalog/create.html'

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.author = self.request.user
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)


class FeedView(TemplateView):
    template_name = 'catalog/feed.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['posts'] = Post.objects.all()
        return context_data


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ("title", "text", "pic", "is_published",)
    success_url = reverse_lazy('catalog:feed')
    template_name = 'catalog/create.html'

    def test_func(self):
        if self.request.user.has_perm('catalog.change_post') or self.get_object().author == self.request.user:
            return True
        else:
            return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('catalog:feed')
    template_name = 'catalog/confirm_delete.html'

    def test_func(self):
        if self.request.user.has_perm('catalog.delete_post') or self.get_object().author == self.request.user:
            return True
        else:
            return False


class ProductsFeedView(LoginRequiredMixin, TemplateView):
    template_name = 'catalog/products_feed.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['products'] = Product.objects.all()
        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.create_product'
    success_url = reverse_lazy('catalog:products feed')
    template_name = 'catalog/create.html'

    def form_valid(self, form):
        product = form.save(commit=False)
        product.author = self.request.user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products feed')
    template_name = 'catalog/create.html'

    def test_func(self):
        if self.get_object().author == self.request.user:
            return True
        elif self.request.user.groups.filter(name='ProductModer').exists():
            self.form_class = ProductModerForm
            return True
        else:
            return False


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'

    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data(**kwargs)
    #     context_data['versions'] = Version.objects.all()
    #     return context_data


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products feed')
    template_name = 'catalog/confirm_delete_product.html'

    def test_func(self):
        if self.request.user.has_perm('catalog.delete_product') or self.get_object().author == self.request.user:
            return True
        else:
            return False


class Joke(TemplateView):
    template_name = 'catalog/joke.html'


class VersionCreateView(LoginRequiredMixin, CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:products feed')
    template_name = 'catalog/create.html'


class VersionUpdateView(LoginRequiredMixin, UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:products feed')
    template_name = 'catalog/create.html'


class VersionDeleteView(LoginRequiredMixin, DeleteView):
    model = Version
    success_url = reverse_lazy('catalog:products feed')
    template_name = 'catalog/confirm_delete_product.html'


class ProductVersionsView(DetailView):
    template_name = 'catalog/versions_view.html'
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLED:
            versions_list = cache.get(f'version_set_{self.object.pk}')
            if versions_list is None:
                versions_list = self.object.version_set.all()
                cache.set(f'version_set_{self.object.pk}', versions_list)
        else:
            versions_list = self.object.version_set.all()

        context_data['versions'] = versions_list

        return context_data


class CategoryListView(ListView):
    model = Category
    template_name = 'catalog/category_all.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        command = GetCachedCategories.get_cached_list()
        context_data['objects'] = command.get_cached_list()

        return context_data


# def home(request):
#     items = Product.objects.all()
#     context = {
#         'products': items
#     }
#     return render(request, 'catalog/home.html', context)

catalog/templates/catalog/access_denied.html
{% extends 'catalog/base.html' %}


{% block content %}
    <h2>You cant post on this site unless you are logged in</h2>
{% endblock %}

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>


<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Store</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/feed/products">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="/feed/">Новости</a>
        {% if user.is_authenticated %}
        <h4><a href="/users/user/{{user.pk}}">{{user.name}}</a></h4>
            <a href="/users/logout">Выйти</a>
        {% else %}
            <a href="/users/login">Войти</a>
            <a href="/users/register">Зарегистрироваться</a>
        {% endif %}

    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Store</h1>
</div>

{% block content %}
{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Store
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/feed/">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url catalog:contacts}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/category_all.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
        {% for object in objects %}
            <h1>{{object.name}}</h1>
        {% endfor %}

{% endblock %}

catalog/templates/catalog/confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="col-6">
        <div class="card">
          <div class = "card-body">
            <form method="post">
              {% csrf_token %}
                <p>Хотите удалить {{ object.title }}?</p>
              <button type="submit">Подтвердить</button>
              <a href="/feed/">Отмена</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/confirm_delete_product.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="col-6">
        <div class="card">
          <div class = "card-body">
            <form method="post">
              {% csrf_token %}
                <p>Хотите удалить {{ object.name }}?</p>
              <button type="submit">Подтвердить</button>
              <a href="/feed/">Отмена</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>
</div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
        </div>
    </footer>

        {% endblock %}

catalog/templates/catalog/create.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="col-6">
        <div class="card">
          <div class = "card-body">
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit">Подтвердить</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/feed.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
    <a href="/create/">Написать пост</a>
    {% for post in posts %}
    {% if post.is_published is True %}
        <div class="container">
            <div class="row text-center">
                <div class="col-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h1 class="my-0 font-weight-normal">{{post.title}}</h1>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>- posted {{post.date}}</li>
                                <li>- {{post.views}} views</li>


                            </ul>
                            <a class="text-muted" href="{{ post.slug }}">Открыть</a>
                            {% if perms.catalog.change_post  or post.author == user %}
                            <a class="text-muted" href="/feed/edit/{{ post.slug }}">Отредактировать</a>
                            {% endif %}
                            {% if perms.catalog.delete_post  or post.author == user %}
                            <a class="text-muted" href="/feed/delete/{{ post.slug }}">Удалить</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    {% endfor %}
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
    <h1>Some stuff on the home page</h1>
{% endblock %}

catalog/templates/catalog/joke.html
<h1>So bad but you can't actually buy anything here</h1>

catalog/templates/catalog/post_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="container">
        <div class="row text-center">
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h1 class="my-0 font-weight-normal">{{post.title}}</h1>
                    </div>
                    <div class="card-body">
                        <img src="{{ post.pic|mediapath }}"/>
                        <h4> {{post.text}} </h4>

                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- posted {{post.date}}</li>
                            <li>- by: {{post.author.first_name}} {{post.author.last_name}}</li>
                            <li>- {{post.views}} views</li>

                        </ul>
                        {% if perms.catalog.change_post  or post.author == user %}
                        <a class="text-muted" href="/feed/edit/{{ post.slug }}">Отредактировать</a>
                        {% endif %}
                        {% if perms.catalog.delete_post  or post.author == user %}
                        <a class="text-muted" href="/feed/delete/{{ post.slug }}">Удалить</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="container">
        <div class="row text-center">
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h1 class="my-0 font-weight-normal">{{object.name}}</h1>
                    </div>
                    <div class="card-body">
                        <img src="{{ object.preview|mediapath }}"/>
                        <h4> {{object.desc}} </h4>

                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- cost {{object.price}}</li>
                            <li>- owner's email: {{object.author}} </li>
                        </ul>

                        {% for version in object.version_set.all %}
<!--                            {% if version.product.name == object.name %}-->
                                {% if version.is_active is True %}
                                    <h4>Версия: {{version.name}} {{version.number}}</h4>
                                {% endif %}
<!--                            {% endif %}-->
                        {% endfor %}
                        <a class="text-muted" href="{{object.pk}}/versions/">Посмотреть все версии продукта</a>
                        {% if perms.catalog.change_product or product.author == user %}
                        <a class="text-muted" href="/feed/products/update/{{object.pk}}">Отредактировать</a>
                        {% endif %}
                        {% if perms.catalog.delete_product or product.author == user %}
                        <a class="text-muted" href="/feed/products/delete/{{object.pk}}">Удалить</a>
                        {%endif%}

                        <a class="text-muted" href="/joke">Купить</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/products_feed.html
{% extends 'catalog/base.html' %}
{% load my_tags %}


{% block content %}

<a href='/feed/products/create'>Добавить товар</a>
<a href='/feed/products/create_version'>Добавить версию товара</a>
    {% for product in products %}
    {% if product.is_published %}
    <div class="container">
        <div class="row text-center">
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h2 class="my-0 font-weight-normal">{{product.name}}</h2>
                    </div>
                    <div class="card-body">
                        <img src="{{ product.preview|mediapath }}"/>
                        <h3 class="card-title pricing-card-title">{{product.price}}</h3>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- {{product.desc}}</li>
                            <li>- {{product.category}}</li>
                            <li>- {{product.date}}</li>
                        </ul>
                        <button type="button" class="btn btn-lg btn-block btn-outline-primary"><a href="/joke">Купить</a></button>
                        {% if perms.catalog.change_product  or product.author == user %}
                        <a href='products/update/{{product.pk}}'>Редактировать</a>
                        {% endif %}
                        <a href='products/product/{{product.pk}}'>Посмотреть</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
{% endblock %}

catalog/templates/catalog/versions_view.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
{% for version in versions %}
<!--  {% if version.product.name == object.name %}-->
    <h4>Название: {{version.name}}</h4>
    <h4>Номер: {{version.number}}</h4>
    <h4>Активна: {{version.is_active}}</h4>
    <a href='/feed/products/delete_version/{{version.pk}}'>Удалить версию</a>
    <a href='/feed/products/edit_version/{{version.pk}}'>Редактировать версию</a>
<!--  {% endif %}-->
{% endfor %}
{% endblock %}